<div class="nw_footer_wrap">
			<div class="nw_f_grid">
				<div class="fgrid_conten">
					<div class="fgc_item_01 gc_item">
						<dl class="news_footer">
						    <!--<dt>新闻动态</dt>
							<dd><a href="">【系统升级】交易市场自定义刷单机器人</a></dd>
							<dd><a href="">【开发动态】交易市场数据实时更新优化</a></dd>
							<dd><a href="">【注册空投】优化注册空投功能</a></dd> -->
						</dl>
						<a class="fgc_href" href="/articleList.html">查看全部</a>
					</div>
					
					<div class="fgc_item_03 gc_item">
						<dl>
							<dt>产品</dt>
							<!--<dd><a href="/php-trade.html">交易所系统（PHP版）</a></dd>
							<dd><a href="/java-trade.html">交易所系统（JAVA版）</a></dd>
							<dd><a href="/news.html" target="_black">区块链财经媒体系统</a></dd>-->
						</dl>
					</div>
					<div class="fgc_item_04 gc_item">
						<dl>
							<dt>解决方案</dt>
							<dd><a href="/wallet.html">钱包对接服务</a></dd>
							<dd><a href="/security.html">区块链安全服务</a></dd>
							<dd><a href="/project.html">项目流量服务</a></dd>
						</dl>
					</div>
					<div class="fgc_we">
						<div class="we_left">
							<p style='color: #B6C0CC;padding-bottom: 15px;'>关于</p>
							<p onclick="location.href='/contact.html'" style="cursor: pointer;">联系我们</p>
							<!-- <p class="we_phone contact_personal"></p> -->
							<p class="we_phone contact_official"></p>
							<p class="feedback"></p>
						</div>
						<div class="we_right">
							<div style="display: inline-block;">
								<img  class="usCode" src="./images/weixin.png" style="width:100px;height:100px; margin-right: 20px;" />
								<p style="color: #889099;text-align: center;margin-top: 15px;font-size: 16px; margin-right: 20px;">微信咨询</p>
							</div>
							<div style="display: inline-block;">
								<img   src="./images/weixin2.png" style="width:100px;height:100px;" />
								<p style="color: #889099;text-align: center;margin-top: 15px;font-size: 16px;">微信咨询</p>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			<div class="nw_f_link">
				<span>友情链接:</span>
			</div>
			<div class="nw_f_inter">
				<b>
				 	<img src="./images/ba_ico.png" style="display: inline-block;vertical-align: middle;margin-right: 5px;margin-left: 10px;"  /> 
					<b class="beiAnCode" ></b>
					<span>
						International | 中国站
					</span>
				</p>
			</div>
		</div>
		<div id="mycontents">
			
		</div>
		<script src="https://www.alicms.com/js/common.js"></script>
		<script src="https://www.alicms.com/js/config.js"></script>
		<script src="https://www.alicms.com/js/main.js"></script>
		<script>
			var _hmt = _hmt || [];
			(function() {
				var hm  = document.createElement("script");
				hm.src ="https://hm.baidu.com/hm.js?43e08b3531a494fb41cde9bdb4ab0f53";
		var s = document.getElementsByTagName("script")[0]; 
				s.parentNode.insertBefore(hm, s);
		})();
		</script>